package com.hj.bean;

import java.util.Date;

public class AlarmDeviceBean {
	
	private MemberBean member;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.ENTERPRISE_ID
     *
     * @mbg.generated
     */
    private String enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.FACTORY
     *
     * @mbg.generated
     */
    private String factory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.MODEL
     *
     * @mbg.generated
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.IDNUM
     *
     * @mbg.generated
     */
    private String idnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.LAST_MODIFY_TIME
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.AREA
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.ADDR
     *
     * @mbg.generated
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.PASSWD
     *
     * @mbg.generated
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.PID
     *
     * @mbg.generated
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.MEMBER_ID
     *
     * @mbg.generated
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.INSTALL_TIME
     *
     * @mbg.generated
     */
    private Date installTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.INSTALL_ADDR
     *
     * @mbg.generated
     */
    private String installAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.EMP_ID
     *
     * @mbg.generated
     */
    private String empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.EMP_NAME
     *
     * @mbg.generated
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.PROJECT_ID
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_device.INVALID_TIME
     *
     * @mbg.generated
     */
    private Date invalidTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.ID
     *
     * @return the value of alarm_device.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.ID
     *
     * @param id the value for alarm_device.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.ENTERPRISE_ID
     *
     * @return the value of alarm_device.ENTERPRISE_ID
     *
     * @mbg.generated
     */
    public String getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.ENTERPRISE_ID
     *
     * @param enterpriseId the value for alarm_device.ENTERPRISE_ID
     *
     * @mbg.generated
     */
    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.TYPE
     *
     * @return the value of alarm_device.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.TYPE
     *
     * @param type the value for alarm_device.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.NAME
     *
     * @return the value of alarm_device.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.NAME
     *
     * @param name the value for alarm_device.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.FACTORY
     *
     * @return the value of alarm_device.FACTORY
     *
     * @mbg.generated
     */
    public String getFactory() {
        return factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.FACTORY
     *
     * @param factory the value for alarm_device.FACTORY
     *
     * @mbg.generated
     */
    public void setFactory(String factory) {
        this.factory = factory == null ? null : factory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.MODEL
     *
     * @return the value of alarm_device.MODEL
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.MODEL
     *
     * @param model the value for alarm_device.MODEL
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.IDNUM
     *
     * @return the value of alarm_device.IDNUM
     *
     * @mbg.generated
     */
    public String getIdnum() {
        return idnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.IDNUM
     *
     * @param idnum the value for alarm_device.IDNUM
     *
     * @mbg.generated
     */
    public void setIdnum(String idnum) {
        this.idnum = idnum == null ? null : idnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.STATUS
     *
     * @return the value of alarm_device.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.STATUS
     *
     * @param status the value for alarm_device.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.LAST_MODIFY_TIME
     *
     * @return the value of alarm_device.LAST_MODIFY_TIME
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for alarm_device.LAST_MODIFY_TIME
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.AREA
     *
     * @return the value of alarm_device.AREA
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.AREA
     *
     * @param area the value for alarm_device.AREA
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.ADDR
     *
     * @return the value of alarm_device.ADDR
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.ADDR
     *
     * @param addr the value for alarm_device.ADDR
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.USER_NAME
     *
     * @return the value of alarm_device.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.USER_NAME
     *
     * @param userName the value for alarm_device.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.PASSWD
     *
     * @return the value of alarm_device.PASSWD
     *
     * @mbg.generated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.PASSWD
     *
     * @param passwd the value for alarm_device.PASSWD
     *
     * @mbg.generated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.PID
     *
     * @return the value of alarm_device.PID
     *
     * @mbg.generated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.PID
     *
     * @param pid the value for alarm_device.PID
     *
     * @mbg.generated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.MEMBER_ID
     *
     * @return the value of alarm_device.MEMBER_ID
     *
     * @mbg.generated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.MEMBER_ID
     *
     * @param memberId the value for alarm_device.MEMBER_ID
     *
     * @mbg.generated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.INSTALL_TIME
     *
     * @return the value of alarm_device.INSTALL_TIME
     *
     * @mbg.generated
     */
    public Date getInstallTime() {
        return installTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.INSTALL_TIME
     *
     * @param installTime the value for alarm_device.INSTALL_TIME
     *
     * @mbg.generated
     */
    public void setInstallTime(Date installTime) {
        this.installTime = installTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.INSTALL_ADDR
     *
     * @return the value of alarm_device.INSTALL_ADDR
     *
     * @mbg.generated
     */
    public String getInstallAddr() {
        return installAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.INSTALL_ADDR
     *
     * @param installAddr the value for alarm_device.INSTALL_ADDR
     *
     * @mbg.generated
     */
    public void setInstallAddr(String installAddr) {
        this.installAddr = installAddr == null ? null : installAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.EMP_ID
     *
     * @return the value of alarm_device.EMP_ID
     *
     * @mbg.generated
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.EMP_ID
     *
     * @param empId the value for alarm_device.EMP_ID
     *
     * @mbg.generated
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.EMP_NAME
     *
     * @return the value of alarm_device.EMP_NAME
     *
     * @mbg.generated
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.EMP_NAME
     *
     * @param empName the value for alarm_device.EMP_NAME
     *
     * @mbg.generated
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.PROJECT_ID
     *
     * @return the value of alarm_device.PROJECT_ID
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.PROJECT_ID
     *
     * @param projectId the value for alarm_device.PROJECT_ID
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_device.INVALID_TIME
     *
     * @return the value of alarm_device.INVALID_TIME
     *
     * @mbg.generated
     */
    public Date getInvalidTime() {
        return invalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_device.INVALID_TIME
     *
     * @param invalidTime the value for alarm_device.INVALID_TIME
     *
     * @mbg.generated
     */
    public void setInvalidTime(Date invalidTime) {
        this.invalidTime = invalidTime;
    }

	public MemberBean getMember() {
		return member;
	}

	public void setMember(MemberBean member) {
		this.member = member;
	}
}