package com.hj.bean;

import java.util.Date;

public class MemberBean {
	
	private String member_id;
	private String member_name;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ACCOUNT_ID
     *
     * @mbg.generated
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.PHONE
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.BUSINESS
     *
     * @mbg.generated
     */
    private String business;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.BAK
     *
     * @mbg.generated
     */
    private String bak;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.IS_DELETE
     *
     * @mbg.generated
     */
    private String isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.REGISTER_TIME
     *
     * @mbg.generated
     */
    private Date registerTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ID
     *
     * @return the value of member.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ID
     *
     * @param id the value for member.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ACCOUNT_ID
     *
     * @return the value of member.ACCOUNT_ID
     *
     * @mbg.generated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ACCOUNT_ID
     *
     * @param accountId the value for member.ACCOUNT_ID
     *
     * @mbg.generated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.TYPE
     *
     * @return the value of member.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.TYPE
     *
     * @param type the value for member.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.PHONE
     *
     * @return the value of member.PHONE
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.PHONE
     *
     * @param phone the value for member.PHONE
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.NAME
     *
     * @return the value of member.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.NAME
     *
     * @param name the value for member.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ADDRESS
     *
     * @return the value of member.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ADDRESS
     *
     * @param address the value for member.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.BUSINESS
     *
     * @return the value of member.BUSINESS
     *
     * @mbg.generated
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.BUSINESS
     *
     * @param business the value for member.BUSINESS
     *
     * @mbg.generated
     */
    public void setBusiness(String business) {
        this.business = business == null ? null : business.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.BAK
     *
     * @return the value of member.BAK
     *
     * @mbg.generated
     */
    public String getBak() {
        return bak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.BAK
     *
     * @param bak the value for member.BAK
     *
     * @mbg.generated
     */
    public void setBak(String bak) {
        this.bak = bak == null ? null : bak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.IS_DELETE
     *
     * @return the value of member.IS_DELETE
     *
     * @mbg.generated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.IS_DELETE
     *
     * @param isDelete the value for member.IS_DELETE
     *
     * @mbg.generated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.REGISTER_TIME
     *
     * @return the value of member.REGISTER_TIME
     *
     * @mbg.generated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.REGISTER_TIME
     *
     * @param registerTime the value for member.REGISTER_TIME
     *
     * @mbg.generated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

	public String getMember_id() {
		return member_id;
	}

	public void setMember_id(String member_id) {
		this.member_id = member_id;
	}

	public String getMember_name() {
		return member_name;
	}

	public void setMember_name(String member_name) {
		this.member_name = member_name;
	}
}