package com.hj.dao;

import java.util.List;

import com.hj.bean.AlarmDeviceBean;

public interface AlarmDeviceBeanMapper {
	
	List<AlarmDeviceBean> selectAll();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_device
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_device
     *
     * @mbg.generated
     */
    int insert(AlarmDeviceBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_device
     *
     * @mbg.generated
     */
    int insertSelective(AlarmDeviceBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_device
     *
     * @mbg.generated
     */
    AlarmDeviceBean selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AlarmDeviceBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AlarmDeviceBean record);
}